# Generated by Django 4.2.16 on 2025-10-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freakfitapp', '0003_razorpayorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('duration', models.PositiveIntegerField()),
                ('zoom_link', models.URLField()),
                ('class_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Classes',
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
