# Generated by Django 4.2.16 on 2025-10-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freakfitapp', '0004_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('description', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
